### ISSUE TITLE
Quick Connect button

### ISSUE THREAD

**Issue by Saborknight** [2bnb/2bnb-extras#33]
Totally stole the idea from GRAD, but having a button on the main menu which directly connects a person to the server would be great, right click allows the user to select an alternative server (such as Kompis's antistasi server).

### Subtasks
- [x] Implement direct connect
- [x] Implement dropdown menu to select different servers
- [ ] ~~Make data modifiable from somewhere other than in the function call~~

**Comment by UrekD** [comment]
Fucking brilliant

**Comment by Saborknight** [comment]
We have been given express permission, even though the mod is GPL anyway, to copy the "Direct Connect" portion of the GRAD mod: https://github.com/gruppe-adler/gruppe_adler_mod/tree/master/addons/ui.

Further, we've been asked that, if we manage to make the button into a dropdown-like function to allow connecting to other servers, then GRAD would pull that portion of our code into their mod. We should endeavour to try and achieve this.

I mean, how hard could it possibly be? :P

**Comment by UrekD** [comment]
I wonder hehe. Tho must say GRAD makes some pretty usefull stuff , we should discuss further at alater date 

_Sent from my Mi A1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Saborknight** [comment]
Well, don't know what there is to discuss in terms of the button and dropdown. There's a lot of enthusiasm for the button despite how small of a feature it actually is, and I can only imagine an addition of the dropdown to go between our servers would be even more welcome.

**Comment by Saborknight** [comment]
The GRAD Direct Connect button, seen in the top left of the screen, to the left of "Singleplayer":
![107410_20190330215506_1](https://user-images.githubusercontent.com/9272259/55275199-b31ef280-5336-11e9-938d-c1f535f58a0e.png)

On right clicking the button:
![107410_20190330215511_1](https://user-images.githubusercontent.com/9272259/55275198-b2865c00-5336-11e9-984b-7352c71940df.png)

So our aim is to firstly implement that button for ourselves, but then secondly to replace that right-click functionality with a dropdown menu. It would probably need a "Go" button in the form of an icon to the right of the dropdown.

**Comment by UrekD** [comment]
> error: Failed to find \x\cba\addons\main\script_macros.hpp.

Any ideas, googling it only reffers to missions..

**Comment by Saborknight** [comment]
Not sure right now, but I'll sort it out when I get to it. It is assigned to me after all :)

**Comment by Saborknight** [comment]
First and second subtasks completed with the above. Since we're using the built in "Spotlight" UI functionality from Arma 3, we didn't need to implement any custom UI elements which GRAD did.

**Comment by Saborknight** [comment]
Done in last commit mentioned below.
